name       : cpio
version    : '2.13'
release    : 13
source     :
    - https://mirrors.rit.edu/gnu/cpio/cpio-2.13.tar.gz : e87470d9c984317f658567c03bfefb6b0c829ff17dbf6b0de48d71a4c8f3db88
homepage   : https://savannah.gnu.org/projects/cpio/
license    : GPL-3.0-or-later
component  : system.base
summary    : a program to manage archives of files
description: |
    GNU cpio is a program to manage archives of files GNU cpio is a tool for creating and extracting archives, or copying files from one place to another.  It handles a number of cpio formats as well as reading and writing tar files.
setup      : |
    %apply_patches
    %reconfigure --bindir=/bin \
               --libexecdir=/tmp \
               --enable-mt \
               --with-rmt=/usr/sbin/rmt
build      : |
    %make
install    : |
    %make_install
    # They don't have a man8 file. Remove directory.
    rmdir $installdir/usr/share/man/man8
