name       : cpio
version    : '2.12'
release    : 11
source     :
    - https://mirrors.rit.edu/gnu/cpio/cpio-2.12.tar.gz : 08a35e92deb3c85d269a0059a27d4140a9667a6369459299d08c17f713a92e73
homepage   : http://www.gnu.org
license    : GPL-3.0-or-later
summary    : a program to manage archives of files
component  : system.base
description: |
    GNU cpio -- a program to manage archives of files GNU cpio is a tool for creating and extracting archives, or copying files from one place to another.  It handles a number of cpio formats as well as reading and writing tar files.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2015-1197.patch
    %patch -p1 < $pkgfiles/security/cve-2016-2037.patch
    %patch -p1 < $pkgfiles/glibc2.25.patch
    sed -i -e '/gets is a/d' gnu/stdio.in.h
    %configure --prefix=/usr\
               --bindir=/bin\
               --libexecdir=/tmp\
               --enable-mt\
               --with-rmt=/usr/sbin/rmt
build      : |
    %make
install    : |
    %make_install
