name        : cpio
version     : 2.11
release     : 9
source      :
    - http://ftp.gnu.org/pub/gnu/cpio/cpio-2.11.tar.bz2 : bb820bfd96e74fc6ce43104f06fe733178517e7f5d1cdee553773e8eff7d5bbd
homepage    : http://www.gnu.org
license     :
    - GPLv3+
summary     : a program to manage archives of files
component   : system.base
description : |
    GNU cpio -- a program to manage archives of files GNU cpio is a tool for creating and extracting archives, or copying files from one place to another.  It handles a number of cpio formats as well as reading and writing tar files.
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2014-9112.patch
    %patch -p1 < $pkgfiles/security/cve-2015-1197.patch
    %patch -p1 < $pkgfiles/security/cve-2016-2037.patch
    sed -i -e '/gets is a/d' gnu/stdio.in.h
    %configure --prefix=/usr\
               --bindir=/bin\
               --libexecdir=/tmp\
               --enable-mt\
               --with-rmt=/usr/sbin/rmt
build      : |
    %make
install    : |
    %make_install
